---
title: "Analysis for all $2/05 data"
author: "Daniel P"
output: html_document
---

This markdown contains most of the code (though I think not all) of the code from your initial crack at analyzing the 2/.05 pilot data for ARL-BV. Your experience running
these models led you to run the clean models the way you did.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(mc.cores=6)
path_to_project_directory <- "~/projects/ARL_bv/"
path_to_arl <- "~/projects/ARL/"
path_to_s22 <- "~/projects/spring_2022_study/"

source(paste0(path_to_s22,"code/functions/s22_utilities.R")) #get s22 functions
source(paste0(path_to_s22,"code/functions/stan_utilities.R"))
source(paste0(path_to_arl,"code/functions/arl_utilities.R")) 
source(paste0(path_to_project_directory,"code/functions/arlbv_utilities.R")) 
source(paste0(path_to_s22,"code/functions/fit_stan_model.R"))

library(tidyverse)
library(lme4)
library(MuMIn)
library(GGally)
library(cmdstanr)
library(tidyverse)
library(tidybayes)
library(loo)
library(bayesplot)
library(sigmoid)

stan_model_dir <- paste0(path_to_project_directory,"code/stan_models/")
model_out_dir <- paste0(path_to_project_directory,"output/results/stan_model_fits/")

trials <- read.csv(paste0(path_to_project_directory,"analysis_data/trial_level_data_all_subs_2023-06-11_11_16_50.csv"))
subs <- read.csv(paste0(path_to_project_directory,"analysis_data/sub_level_data_all_subs_2023-06-11_11_16_50.csv"))
```

```{r}
sub_hard_fail <- subs %>% filter(att_checks_passed < 5 |
                                 valrat_skipped_percent > .1 |
                                 late_percent > .2 |
                                 consecutive_late_choices > 9 |
                                 trials_completed < 144 |
                                 sd_valrat < .1 |
                                 percent_left > .8 |
                                 percent_left < .2 |
                                 percent_left_b1 < .1 |
                                 percent_left_b1 > .9 |
                                 percent_left_b2 < .1 |
                                 percent_left_b2 > .9 |
                                 percent_left_b3 < .1 |
                                 percent_left_b3 > .9 |
                                 answers_incorrect > 2)

#count the number of soft QC cutoffs each subject meets
subs$softs <- 0
for(i in 1:nrow(subs)){
  subs$softs[i] <- length(which(c(subs$att_checks_passed[i] == 5,subs$valrat_skipped_percent[i] > .05, subs$late_percent[i] > .15,
                                  subs$sd_valrat[i] < .13, subs$percent_left[i] > .75, subs$percent_left[i] < .25,
                                  subs$percent_left_b1[i] > .83, subs$percent_left_b1[i] < .17, subs$percent_left_b2[i] > .83, 
                                  subs$percent_left_b2[i] < .17,subs$percent_left_b3[i] > .83, subs$percent_left_b3[i] < .17,subs$answers_incorrect[i] > 1)))
}

sub_soft_fail <- filter(subs,softs >= 2) #identify those who meet more than 2 soft cutoffs

subs_to_exclude <- unique(c(sub_hard_fail$id,sub_soft_fail$id)) #mark subjects who fail on either hard or soft or criteria for exclusion

trials <- trials %>% filter(!(id %in% subs_to_exclude)) %>% filter(choice != "late") 
subs <- subs %>% filter(!(id %in% subs_to_exclude))
```

Data transformations
```{r}
trials <- add_sub_indices(trials) #add subject indices to the df. These will match the indices used in Stan.
trials <- add_probe_number(trials,newcol="rat_number",val_col="valrat_z") #add rating number

#add a column with completed trial numbers - the trial indices if you ignore late trials. These will match the "t" trial numbers used in the Stan models
trials <- do.call(rbind,by(trials,trials$sub_index,add_trials_nl))
trials$overall_trial_nl <- 1:nrow(trials) #get the overall trial number ignoring late trials and collapsing across subjects
```

```{r}
trials_aff <- trials %>% filter(!is.na(valrat_z))
trials_aff <- trials_aff %>% mutate(out_nfr = ifelse(show_fres==0,out,0),
                            out_fres = ifelse(show_fres==1,out,0),
                            bv_fres = ifelse(show_fres==1,box_val,0))
val_fit_res <- lm(valrat_z ~ out_nfr + out_fres, trials_aff)
to_join <- data.frame(resids = resid(val_fit_res),"overall_trial_nl"=trials_aff$overall_trial_nl)
trials <- left_join(trials,to_join)
trials[which(is.na(trials$resids)),"resids"] <- 0

val_fit_fi <- lmer(valrat_z ~ out_nfr + out_fres + bv_fres + (out_nfr + out_fres + bv_fres|id),trials_aff) #predict affect ratings
predicted_val <- predict(val_fit_fi,trials_aff) #get predictions

trials$fi_rat <- trials$valrat_z #filled in affect column
for(row in 1:nrow(trials)){
  if(is.na(trials$fi_rat[row])){
    trials$fi_rat[row] <- predicted_val[row] #if the valrat is NA, replace it with the predicted value
  }
}

```



```{r}
dr_vars <- c("valreg_rsq","bv_b","fres_b","fres_bv_ratio")
plot_sub_level_vars(subs,dr_vars,path_to_project_directory,type="dr") #create and save plot grids
```

```{r}
sub$age <- as.numeric(sub$age)
age_no_skips <- filter(sub,age < 900)
plot_hist(age_no_skips,"age") 
```

```{r}
sum(sub$gender=="Male")
```

```{r}
sum(sub$gender=="Female")
```

```{r}
sum(sub$gender=="Non-binary")
```

```{r}
trials$pair_pres_num <- rep(c(1:48),65*3)
percentage_plots(trials,"stay")
```

## ADJUST FROM HERE ##
```{r}
trials_aff <- trials %>% filter(!is.na(valrat_z))

trials_aff <- trials_aff %>% mutate(out_nfr = ifelse(show_fres==0,out,0),
                            out_fres = ifelse(show_fres==1,out,0),
                            bv_fres = ifelse(show_fres==1,box_val,0),
                            valrat_fres = ifelse(show_fres ==1,valrat_z,0),
                            valrat_nofres = ifelse(show_fres == 1,0,valrat_z))
val_fit <- lm(valrat_z ~ out_nfr + out_fres, trials_aff)
summary(val_fit)

trials_aff$resid <- resid(val_fit)
trials_aff <- trials_aff %>% mutate(resid_fres = ifelse(show_fres==1,resid,0),
                            resid_nofres = ifelse(show_fres==0,resid,0))
```

```{r}
stay_fit <- lmer(stay ~ out_nfr + out_fres + bv_fres + (1|id),trials_aff)
summary(stay_fit)
```

```{r}
low_bv <- filter(subs,bv_b < median(subs$bv_b))
medsplit <- trials %>% filter(id %in% low_bv$id)
stay_medsplit <- lmer(stay ~ out_nfr + out_fres + valrat_fres + (1|id),medsplit)
summary(stay_medsplit)
```
```{r}
stay_test <- lmer(stay ~ out_nfr + out_fres + valrat_fres + (1|id),trials_aff)
summary(stay_test)
```


```{r}
stay_val_fit <- lmer(stay ~ out_nfr + out_fres + resid_fres + resid_nofres + bv_fres + (1|id),trials_aff)
summary(stay_val_fit)
```







# Running/loading models
```{r}
full_model <- fit_stan_model(stan_file=paste0(stan_model_dir,"full_model.stan"),
                                   model_out_dir=model_out_dir,
                                   raw_data=trials,
                                   study = "arlbv",
                                   n_t = 144,
                                   chains = 3)

full_model_nomult <- fit_stan_model(stan_file=paste0(stan_model_dir,"full_model_nomult.stan"),
                                   model_out_dir=model_out_dir,
                                   raw_data=trials,
                                   study = "arlbv",
                                   n_t = 144,
                                   chains = 3)

rew_bv_onedc <- fit_stan_model(stan_file=paste0(stan_model_dir,"rew_bv_onedc.stan"),
                                   model_out_dir=model_out_dir,
                                   raw_data=trials,
                                   study = "arlbv",
                                   n_t = 144,
                                   chains = 3)

rew_bv_onedc_noaff <- fit_stan_model(stan_file=paste0(stan_model_dir,"rew_bv_onedc_noaff.stan"),
                                   model_out_dir=model_out_dir,
                                   raw_data=trials,
                                   study = "arlbv",
                                   n_t = 144,
                                   chains = 3)
bv_onedc <- fit_stan_model(stan_file=paste0(stan_model_dir,"bv_onedc.stan"),
                                     model_out_dir=model_out_dir,
                                     raw_data=trials,
                                     study = "arlbv",
                                     n_t = 144,
                                     chains = 3)
bv_onedc_nols <- fit_stan_model(stan_file=paste0(stan_model_dir,"bv_onedc_nols.stan"),
                                     model_out_dir=model_out_dir,
                                     raw_data=trials,
                                     study = "arlbv",
                                     n_t = 144,
                                     chains = 3)
bv_onedc_noac <- fit_stan_model(stan_file=paste0(stan_model_dir,"bv_onedc_noac.stan"),
                                     model_out_dir=model_out_dir,
                                     raw_data=trials,
                                     study = "arlbv",
                                     n_t = 144,
                                     chains = 3)

rew_afffi_onedc_nols_affnf <- fit_stan_model(stan_file=paste0(stan_model_dir,"rew_afffi_onedc_nols_affnf.stan"),
                                     model_out_dir=model_out_dir,
                                     raw_data=trials,
                                     study = "arlbv",
                                     n_t = 144,
                                     chains = 3)
rew_afffi_onedc_nols_affnf_forgunpres <- fit_stan_model(stan_file=paste0(stan_model_dir,"rew_afffi_onedc_nols_affnf_forgunpres.stan"),
                                             model_out_dir=model_out_dir,
                                             raw_data=trials,
                                             study = "arlbv",
                                             n_t = 144,
                                             chains = 3)

```



```{r}
trials_resid <- 
resid-fit <- lm(valrat_z ~ out_nfr + out_fres, trials_aff)
```

```{r}
full_model$diagnostics
filter(full_model$diagnostics$Rhat, sd != 0)
filter(full_model$diagnostics$ESS, sd != 0)
view(filt_sum(full_model$sum,"(mu|sigma|lOmega\\[2,1\\])"))
```

```{r}
view(filt_sum(full_model_nofor$sum,"(mu|sigma|lOmega\\[2,1\\])"))
```


```{r}
fmd <- full_model$fit$draws()
mcmc_areas(
  fmd,
  area_method = "scaled height",
  pars = "bvf_w_mu[1]",
  prob = 0.8, # 80% intervals
  prob_outer = 0.95, # 99%
  point_est = "mean"
)
```

```{r}
fm_divs <- nuts_params(full_model$fit)
temp <- mcmc_parcoord(fmd,regex_pars="(mu|sigma|lOmega\\[2,1\\])",np = fm_divs)
ggsave("~/Desktop/fm_parcoord.pdf",device="pdf",width=40,height=10)

pairs_fmd <- mcmc_pairs(
              fmd,
              pars = c("bvf_w_mu[1]","bvf_w_tau[1]","bvf_w_mu[2]","bvf_w_tau[2]",
                       "bvf_w_lOmega[2,1]","lrn_b_mu","lrn_b_sigma","dcy_b_mu","dcy_b_sigma"),
              np = fm_divs
            )
ggsave("~/Desktop/pairs_fmd.pdf",pairs_fmd,device="pdf",width = 20, height = 20)
```

```{r}
filter(full_model_nofor$diagnostics$ESS,sd!=0)
```

```{r}
filter(full_model$diagnostics$Rhat,sd!=0)
```

```{r}
fmnd <- full_model_nofor$fit$draws()
 mcmc_areas(
  fmnd,
  area_method = "scaled height",
  pars = "bvf_w_lOmega[2,1]",
  prob = 0.8, # 80% intervals
  prob_outer = 0.9, # 99%
  point_est = "mean"
  )
```
```{r}
view(filt_sum(full_model$sum,"zero"))
```

```{r}
fmnm_draws <- full_model_nomult$fit$draws()
mcmc_areas(
  fmnm_draws,
  area_method = "scaled height",
  pars = "bvf_sens_mu",
  prob = 0.8, # 80% intervals
  prob_outer = 0.95, # 99%
  point_est = "mean"
)
```
```{r}
fmnm_bvsens_draws <- full_model_nomult$fit$draws("bvf_sens_z")
fmnm_bvb_draws <- full_model_nomult$fit$draws("bvf_b_z")
mcmc_areas(
  test,
  area_method = "scaled height",
  prob = 0.8, # 80% intervals
  prob_outer = 0.95, # 99%
  point_est = "mean"
)
```

```{r}
fsml_compare(full_model_nomult,full_model)
```

```{r}
full_model_nomult$diagnostics
```
```{r}
fsml_compare(full_model,full_model_onedc,full_model_nofor)
```

```{r}
filter(full_model_onedc$diagnostics$ESS,sd!=0)
fmonedc <- full_model_onedc$fit$draws(c("bvf_w_mu[2]","bvf_w_lOmega"))
mcmc_areas(
  fmonedc,
  pars = "bvf_w_mu[2]",
  area_method = "scaled height",
  prob = 0.8, # 80% intervals
  prob_outer = 0.95, # 99%
  point_est = "mean"
)
```
```{r}
trials_nofres <- filter(trials_aff,show_fres == 0)
cor(trials_nofres$valrat_z,trials_nofres$out)
```
```{r}
rbo_draws <- rew_bv_onedc$fit$draws(c("bvf_w_mu","bvf_w_lOmega"))
mcmc_areas(
  rbo_draws,
  pars = "bvf_w_lOmega[2,1]",
  area_method = "scaled height",
  prob = 0.8, # 80% intervals
  prob_outer = 0.95, # 99%
  point_est = "mean"
)
```

```{r}
rbon_bs <- rew_bv_onedc_noaff$fit$draws("bvf_sens_mu")
mcmc_areas(
  rbon_bs,
  pars = "bvf_sens_mu",
  area_method = "scaled height",
  prob = 0.8, # 80% intervals
  prob_outer = 0.95, # 99%
  point_est = "mean"
)
```
```{r}
fsml_compare(rew_onedc,rew_bv_onedc_noaff)
```
```{r}
rew_bv_onedc_noaff$diagnostics
```
```{r}
filt_sum(bv_onedc_nonuis$sum,"mu")
bon_draws <- bv_onedc_nonuis$fit$draws("bvf_sens_mu")
mcmc_areas(
  bon_draws,
  pars = "bvf_sens_mu",
  area_method = "scaled height",
  prob = 0.8, # 80% intervals
  prob_outer = 0.95, # 99%
  point_est = "mean"
)
```

```{r}
bv_onedc$diagnostics
bv_onedc_draws <- bv_onedc$fit$draws("bvf_sens_mu")
mcmc_areas(
  bv_onedc_draws,
  pars = "bvf_sens_mu",
  area_method = "scaled height",
  prob = 0.8, # 80% intervals
  prob_outer = 0.95, # 99%
  point_est = "mean"
)
```
```{r}
bv_rewnf$diagnostics
```

```{r}
bvo_draws <- bvo$fit$draws()
bvo_divs <- nuts_params(bvo$fit)
pairs <- mcmc_pairs(bvo_draws,regex_pars = "(mu|sigma)",np = bvo_divs,condition=pairs_condition(draws=.99))
ggsave("~/Desktop/pairs.pdf",pairs,device="pdf",width=20,height=20)
```

```{r}
fsml_compare(bv_onedc_nodc,bv_onedc)
```
```{r}
filter(bv_onedc_nols$diagnostics$Rhat,sd!=0)
```
```{r}
bonl <- bv_onedc_nols$fit$draws("bvf_sens_mu")
mcmc_areas(
  bonl,
  pars = "bvf_sens_mu",
  area_method = "scaled height",
  prob = 0.8, # 80% intervals
  prob_outer = 0.95, # 99%
  point_est = "mean"
)
```
```{r}
bonac <- bv_onedc_noac$fit$draws("bvf_sens_mu")
mcmc_areas(
  bonac,
  pars = "bvf_sens_mu",
  area_method = "scaled height",
  prob = 0.8, # 80% intervals
  prob_outer = 0.95, # 99%
  point_est = "mean"
)
```
```{r}
bondc <- bv_onedc_nodc$fit$draws("bvf_sens_mu")
mcmc_areas(
  bondc,
  pars = "bvf_sens_mu",
  area_method = "scaled height",
  prob = 0.8, # 80% intervals
  prob_outer = 0.95, # 99%
  point_est = "mean"
)
```
```{r}
bonuis <- bv_onedc_nonuis$fit$draws("bvf_sens_mu")
mcmc_areas(
  bondc,
  pars = "bvf_sens_mu",
  area_method = "scaled height",
  prob = 0.8, # 80% intervals
  prob_outer = 0.95, # 99%
  point_est = "mean"
)
```
```{r}
bvon <- bv_onedc_nonuis_fit$draws("bvf_sens_mu")
mcmc_areas(
  bvon,
  pars = "bvf_sens_mu",
  area_method = "scaled height",
  prob = 0.8, # 80% intervals
  prob_outer = 0.95, # 99%
  point_est = "mean"
)
```

```{r}
fsml_compare(rew_aff_onedc_nols_affnf,rew_onedc_nols_affnf)
```

```{r}
raona <- rew_aff_onedc_nols_affnf$fit$draws("af_sens_mu")
mcmc_areas(
  raona,
  area_method = "scaled height",
  prob = 0.8, # 80% intervals
  prob_outer = 0.95, # 99%
  point_est = "mean"
)
```
```{r}
filt_sum(rew_aff_onedc_nols_affnf$sum,"mu")
```

```{r}
fsml_compare(rew_aff_onedc_nols_affnf_md,rew_onedc_nols_affnf_md)
```

```{r}
raona_md <- rew_aff_onedc_nols_affnf_md$fit$draws("anf_sens_mu")
mcmc_areas(
  raona_md,
  area_method = "scaled height",
  prob = 0.8, # 80% intervals
  prob_outer = 0.95, # 99%
  point_est = "mean"
)
```

```{r}
fsml_compare(rew_afffi_onedc_nols_affnf,rew_afffi_onedc_nols_affnf_sepreps)
```

```{r}
raona<- rew_afffi_onedc_nols_affnf$fit$draws("lrn_a_mu")
mcmc_areas(
  raona,
  area_method = "scaled height",
  prob = 0.8, # 80% intervals
  prob_outer = 0.95, # 99%
  point_est = "mean"
)
```

