---
title: "data_review_3_23"
author: "Daniel P"
date: '2023-03-09'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
path_to_project_directory <- "~/projects/ARL/"
path_to_s22 <- "~/projects/spring_2022_study/"

source(paste0(path_to_s22,"code/functions/s22_utilities.R")) #get s22 functions
source(paste0(path_to_project_directory,"code/functions/arl_utilities.R")) 
library(tidyverse)
library(lme4)
```

```{r}
sub <- read.csv(paste0(path_to_project_directory,"analysis_data/sub_level_data_all_subs_2023-03-13_18_50_55.csv")) %>% filter(.,!(id %in% c(87145,87877,88816,85663)))

tl_data <- read.csv(paste0(path_to_project_directory,"analysis_data/trial_level_data_all_subs_2023-03-13_18_50_55.csv")) %>% filter(.,!(id %in% c(87145,87877,88816,85663)))
```


```{r}
dr_vars <- c("reward_b","fo_b","valreg_rsq","avd_affect","avd_reward","percent_hi_aff","percent_hi_reward","rew_fo_ratio")
plot_sub_level_vars(sub,dr_vars,path_to_project_directory,type="dr") #create and save plot grids
```

```{r}
sub$age <- as.numeric(sub$age)
age_no_skips <- filter(sub,age < 900)
plot_hist(age_no_skips,"age") 
```

```{r}
sum(sub$gender=="Male")
```

```{r}
sum(sub$gender=="Female")
```

```{r}
sum(sub$gender=="Non-binary")
```

```{r}
trials_nl <- filter(tl_data,choice != "late") #filter out late trials
trials_aff <- filter(trials_nl,pair_type == "affect")
percentage_plots(trials_aff,"hi_chosen")
```

```{r}
trials_rew <- filter(trials_nl,pair_type == "reward")
percentage_plots(trials_rew,"hi_chosen")
```
```{r}
percentage_plots(trials_nl,"stay")
```
```{r}
trials_aff <- filter(tl_data,!is.na(val_rat))
val_fit <- lmer(valrat_z ~ reward + fake_out + (reward + fake_out|id), trials_aff)
val_fit2 <- lmer(valrat_z ~ reward + (reward|id), trials_aff)
summary(val_fit)
r.squaredGLMM(val_fit)

test <- residuals(val_fit)
```

```{r}
cor(trials_aff$reward,trials_aff$valrat_z)
```

