---
title: "data_review_4_17"
author: "Daniel P"
date: '2023-04-17'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
path_to_project_directory <- "~/projects/ARL_bv/"
path_to_arl <- "~/projects/ARL/"
path_to_s22 <- "~/projects/spring_2022_study/"

source(paste0(path_to_s22,"code/functions/s22_utilities.R")) #get s22 functions
source(paste0(path_to_arl,"code/functions/arl_utilities.R")) 
library(tidyverse)
library(lme4)
library(MuMIn)
```

```{r}
exclude_subs <- c(79948,79993,87319,87358,89626,89749,88189,89623,90172,87580,89773,89833,89509,84610,89935,89416,89788,89587,89536,89167,87316,79864)
sub <- read.csv(paste0(path_to_project_directory,"analysis_data/old_analysis_data/sub_level_data_all_subs_2023-05-03_16_58_20.csv")) %>% filter(.,!(id %in% exclude_subs))

tl_data <- read.csv(paste0(path_to_project_directory,"analysis_data/old_analysis_data/trial_level_data_all_subs_2023-05-03_16_58_20.csv")) %>% filter(.,!(id %in% exclude_subs))
```


```{r}
dr_vars <- c("valreg_rsq","bv_b","fres_b","fres_bv_ratio","percent_left_b1","percent_left_b2","percent_left_b3")
plot_sub_level_vars(sub,dr_vars,path_to_project_directory,type="dr") #create and save plot grids
```

```{r}
sub$age <- as.numeric(sub$age)
age_no_skips <- filter(sub,age < 900)
plot_hist(age_no_skips,"age") 
```

```{r}
sum(sub$gender=="Male")
```

```{r}
sum(sub$gender=="Female")
```

```{r}
sum(sub$gender=="Non-binary")
```

```{r}
trials_nl <- filter(tl_data,choice != "late")
trials_nl$pair_pres_num <- rep(c(1:48),nrow(sub)*3)
percentage_plots(trials_nl,"stay")
```

```{r}
trials <- tl_data %>% mutate(out_nfr = ifelse(show_fres==0,out,0),
                                    out_fres = ifelse(show_fres==1,out,0),
                                    bv_fres = ifelse(show_fres==1,box_val,0),
                                    valrat_fres = ifelse(show_fres ==1,valrat_z,0),
                                    valrat_nofres = ifelse(show_fres == 1,0,valrat_z))
trials_aff <- filter(trials,!is.na(valrat_z))
val_fit <- lm(valrat_z ~ out_nfr + out_fres + bv_fres, trials_aff)
summary(val_fit)
```

```{r}
stay_fit <- lmer(stay ~ out_nfr + out_fres + bv_fres + (1|id),trials)
summary(stay_fit)
```

```{r}
low_bv <- filter(sub,bv_b < -.025)
medsplit <- trials %>% filter(id %in% low_bv$id)
stay_medsplit <- lmer(stay ~ out_nfr + out_fres + bv_fres + (1|id), medsplit)
summary(stay_medsplit)
```

```{r}
stay_val_fit <- lmer(stay ~ out_nfr + out_fres + valrat_fres + valrat_nofres + (1|id),trials_aff)
summary(stay_val_fit)
```

