---
title: "data_review_4_17"
author: "Daniel P"
date: '2023-04-17'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
path_to_project_directory <- "~/projects/ARL_bv/"
path_to_arl <- "~/projects/ARL/"
path_to_s22 <- "~/projects/spring_2022_study/"

source(paste0(path_to_s22,"code/functions/s22_utilities.R")) #get s22 functions
source(paste0(path_to_arl,"code/functions/arl_utilities.R")) 
library(tidyverse)
library(lme4)
library(MuMIn)
```

```{r}
include_subs <- c(
"62b05d0902f003ad813fcc44",
"61109146680cc2b440c01c2a",
"5e837e917441520b9c662931",
"58a477c660cd820001e9a5d6",
"5e987098f1bb6707dca13f5b",
"62e2d5c238c450c3579dfa91",
"5bc151ece6491a00013a21f3",
"60f6cd4f42b3b160be558774",
"612d227e68d8bf942e6091da",
"59014ee029f42300013cc5b7",
"5ae21dfffef71c0001be9caf",
"630386f64c5bbd56ab1c3b0f",
"5d531dbf8c48ca00018560a7",
"5e4aa3729d301e000cf8ced9",
"60c3f23e89a2b54322a2d861",
"58d2cb10f5899100018a05b8",
"5f58d7941af44708223b94da",
"614ee5e28a2f0a07d4d639dd",
"5e7d031be805560ae6b93dba")


trials <- read.csv(paste0(path_to_project_directory,"analysis_data/old_analysis_data/trial_level_data_all_subs_2023-05-17_13_23_36.csv")) %>% filter(id %in% include_subs) %>% filter(choice != "late")
sub <- read.csv(paste0(path_to_project_directory,"analysis_data/old_analysis_data/sub_level_data_all_subs_2023-05-17_13_23_36.csv")) %>% filter(id %in% include_subs)

```


```{r}
dr_vars <- c("valreg_rsq","bv_b","fres_b","fres_bv_ratio","percent_left_b1","percent_left_b2","percent_left_b3","percent_left")
plot_sub_level_vars(sub,dr_vars,path_to_project_directory,type="dr") #create and save plot grids
```

```{r}
sub$age <- as.numeric(sub$age)
age_no_skips <- filter(sub,age < 900)
plot_hist(age_no_skips,"age") 
```

```{r}
sum(sub$gender=="Male")
```

```{r}
sum(sub$gender=="Female")
```

```{r}
sum(sub$gender=="Non-binary")
```

```{r}
trials$pair_pres_num <- rep(c(1:48),nrow(sub)*3)
percentage_plots(trials,"stay")
```

```{r}
trials_aff <- trials %>% filter(!is.na(valrat_z))

trials_aff <- trials_aff %>% mutate(out_nfr = ifelse(show_fres==0,out,0),
                            out_fres = ifelse(show_fres==1,out,0),
                            bv_fres = ifelse(show_fres==1,box_val,0),
                            valrat_fres = ifelse(show_fres ==1,valrat_z,0),
                            valrat_nofres = ifelse(show_fres == 1,0,valrat_z))
val_fit <- lm(valrat_z ~ out_nfr + out_fres + bv_fres, trials_aff)
summary(val_fit)

```

```{r}
stay_fit <- lmer(stay ~ out_nfr + out_fres + bv_fres + (1|id),trials_aff)
summary(stay_fit)
```

```{r}
low_bv <- filter(sub,bv_b < -.02)
medsplit <- trials_aff %>% filter(id %in% low_bv$id)
stay_medsplit <- lmer(stay ~ out_nfr + out_fres + bv_fres + (1|id),medsplit)
summary(stay_medsplit)
```

```{r}
stay_val_fit <- lmer(stay ~ out_nfr + out_fres + valrat_fres + valrat_nofres + (1|id),trials_aff)
summary(stay_val_fit)
```

