---
title: "S22-2 Simulations"
author: "Daniel P"
date: '2023-01-20'
output: html_document
---

Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
path_to_project_directory <- "~/projects/ARL/"

files2source <- list.files(paste0(path_to_project_directory,"code/sim_funcs"),full.names=TRUE)
sapply(files2source,source)
source("~/projects/spring_2022_study/code/functions/s22_utilities.R")

library(profvis)
```

```{r}
prob_r_init <- rbind(c(rep(1/11,11)),
                   c(rep(1/11,11)),
                   c(rep(0,4),rep(1/7,7)),
                   c(rep(1/7,7),rep(0,4)))
prob_fo_init <- rbind(c(.2,.3,.2,.05,.05,.05,.03,.03,.03,.03,.03),
                    c(.03,.03,.03,.03,.03,.05,.05,.05,.2,.3,.2),
                    c(0,0,0,0,.05,.1,.2,.3,.2,.1,.05),
                    c(.05,.1,.2,.3,.2,.1,.05,0,0,0,0))
prob_fo_agg_rs_15 <- rbind(c(.3,.2,.12,.07,.06,.05,.05,.04,.04,.04,.03),
                     c(0.03,0.04,0.04,0.04,0.05,0.05,0.06,0.07,0.12,0.2,0.3),
                     c(rep(0,4),0.1,0.1,0.11,0.12,0.14,0.18,0.25),
                     c(.25,.18,.14,.12,.11,.1,.1,rep(0,4)))



c(0,0,0,0,.05,.1,.2,.3,.2,.1,.05),

sim_a1 <- simulate_s222(n_samp=100,ns=50,nb=2,n_pb=2,n_tp=28,alpha_r_mean=.1,beta_r_mean=1,beta_r_sd=.7,alpha_a_mean=.1,beta_a_mean=1,beta_a_sd=.7,phi_mean=1,
                phi_sd=.7,tau_mean=.25,tau_sd=.2,w_r_mean=4,w_fo_mean=-2,w_q_mean=-.5,w_opv_mean=-.5,prob_r=prob_r_init,prob_fo=prob_fo_init)
save_sim(sim_a1,path_to_project_directory)
sim_a2 <- simulate_s222(n_samp=100,ns=50,nb=2,n_pb=2,n_tp=28,alpha_r_mean=.2,beta_r_mean=1,beta_r_sd=.7,alpha_a_mean=.2,beta_a_mean=1,beta_a_sd=.7,phi_mean=1,
                phi_sd=.7,tau_mean=.25,tau_sd=.2,w_r_mean=4,w_fo_mean=-2,w_q_mean=-.5,w_opv_mean=-.5,prob_r=prob_r_init,prob_fo=prob_fo_init)
save_sim(sim_a2,path_to_project_directory)


prob_r_concentrated <- rbind(c(.05,.05,.05,.1,.15,.2,.15,.1,.05,.05,.05),
                             c(.05,.05,.05,.1,.15,.2,.15,.1,.05,.05,.05),
                             c(rep(0,4),.05,.1,.2,.3,.2,.1,.05),
                             c(.05,.1,.2,.3,.2,.1,.05,rep(0,4)))
sim_a1_conc <- simulate_s222(n_samp=100,ns=50,nb=2,n_pb=2,n_tp=28,alpha_r_mean=.1,beta_r_mean=1,beta_r_sd=.7,alpha_a_mean=.1,beta_a_mean=1,beta_a_sd=.7,phi_mean=1,
                phi_sd=.7,tau_mean=.25,tau_sd=.2,w_r_mean=4,w_fo_mean=-2,w_q_mean=-.5,w_opv_mean=-.5,prob_r=prob_r_concentrated,prob_fo=prob_fo_init)
save_sim(sim_a1_conc,path_to_project_directory)
sim_a2_conc <- simulate_s222(n_samp=100,ns=50,nb=2,n_pb=2,n_tp=28,alpha_r_mean=.2,beta_r_mean=1,beta_r_sd=.7,alpha_a_mean=.2,beta_a_mean=1,beta_a_sd=.7,phi_mean=1,
                phi_sd=.7,tau_mean=.25,tau_sd=.2,w_r_mean=4,w_fo_mean=-2,w_q_mean=-.5,w_opv_mean=-.5,prob_r=prob_r_concentrated,prob_fo=prob_fo_init)
save_sim(sim_a2_conc,path_to_project_directory)


sim_a1_ab0 <- simulate_s222(n_samp=100,ns=50,nb=2,n_pb=2,n_tp=28,alpha_r_mean=.1,beta_r_mean=1,beta_r_sd=.7,alpha_a_mean=.1,beta_a_mean=0,beta_a_sd=0,phi_mean=2,
                phi_sd=.7,tau_mean=.25,tau_sd=.2,w_r_mean=4,w_fo_mean=-2,w_q_mean=-.5,w_opv_mean=-.5,prob_r=prob_r_init,prob_fo=prob_fo_init)

sim_a2_50 <- simulate_s222(n_samp=100,ns=50,nb=1,n_pb=2,n_tp=60,alpha_r_mean=.2,beta_r_mean=1,beta_r_sd=.7,alpha_a_mean=.2,beta_a_mean=.25,beta_a_sd=0,phi_mean=2,
                phi_sd=.7,tau_mean=.25,tau_sd=.2,w_r_mean=4,w_fo_mean=-2,w_q_mean=-.5,w_opv_mean=-.5,prob_r=prob_r_init,prob_fo=prob_fo_init)

sim_a1_ab25_60 <- simulate_s222(n_samp=100,ns=50,nb=1,n_pb=2,n_tp=60,alpha_r_mean=.2,beta_r_mean=1,beta_r_sd=.7,alpha_a_mean=.1,beta_a_mean=.25,beta_a_sd=0,phi_mean=2,
                phi_sd=.7,tau_mean=.25,tau_sd=.2,w_r_mean=4,w_fo_mean=-2,w_q_mean=-.5,w_opv_mean=-.5,prob_r=prob_r_init,prob_fo=prob_fo_init)


#maybe more concentrated would help?
prob_fo_tight <- rbind(c(0,0,.5,.5,0,0,0,0,0,0,0),
                    c(0,0,0,0,0,0,0,.5,.5,0,0),
                    c(0,0,0,0,.05,.1,.2,.3,.2,.1,.05),
                    c(.05,.1,.2,.3,.2,.1,.05,0,0,0,0))
sim_a2_fotight <- simulate_s222(n_samp=100,ns=50,nb=1,n_pb=2,n_tp=60,alpha_r_mean=.2,beta_r_mean=1,beta_r_sd=.7,alpha_a_mean=.2,beta_a_mean=.25,beta_a_sd=0,phi_mean=2,
                phi_sd=.7,tau_mean=.25,tau_sd=.2,w_r_mean=4,w_fo_mean=-2,w_q_mean=-.5,w_opv_mean=-.5,prob_r=prob_r_init,prob_fo=prob_fo_tight)
```


```{r}
sim_a15$lcg_list[[2]]
```

```{r}
sim_a15_fskew$d_cor_grid
sim_a15_badaff$d_cor_grid
sim_a15_badaff_pseun$d_cor_grid
```

```{r}
prob_r_wseq <- rbind(c(rep(NA,11)),
                c(rep(NA,11)),
                c(rep(0,4),rep(1/7,7)),
                c(rep(1/7,7),rep(0,4)))
r_seq_psueduni <- rbind(c(1,-3,-2,4,0,3,-5,2,5,-1,-4,0,2,1,1,-4,-4,4,2,-2,-4,0,1,3,2,-3,4,-3),
               c(-4,0,1,3,5,-2,1,-4,-2,1,3,-2,-2,0,1,1,5,-1,-4,0,3,-2,1,-2,1,3,-2,-2),
               c(rep(NA,28)),
               c(rep(NA,28)))

sim_a15$d_cor_grid
sim_a15_pseun$d_cor_grid
sim_a15_pseun$pred_cor_grid
sim_a15_pseun$lcg_list[[1]]
sim_a15$lcg_list[[1]]
sim_a15$lcg_list[[1]]
sim_a15_pseun_fskew$d_cor_grid
sim_a15_pseun$lcg_list[[1]]
sim_a15_fskew$lcg_list[[2]]
sim_a15_pseun_fskew$lcg_list[[1]]
sim_a15_pseun_fskew$lcg_list[[2]]
sim_a15_valnoise$d_cor_grid
sim_a15$d_cor_grid
sim_a15_valnoise_skew$d_cor_grid
sim_a15_fskew$lcg_list[[1]]

sim_a15_valnoise$lcg_list[[2]]
sim_a15_valnoise_skew$lcg_list[[2]]
sim_a15_valnoise$lcg_list[[1]]
sim_a15_valnoise_skew$lcg_list[[2]]
```

```{r}
sim_skewpe$d_cor_grid
```

```{r}
plot_df1 <- sim_a15_valnoise_skew$plot_df_list[[1]] %>% mutate(pair="Affect pair",trial=1:nrow(sim_a15_valnoise_skew$plot_df_list[[1]]))
plot_df2 <- sim_a15_valnoise_skew$plot_df_list[[2]] %>% mutate(pair="Reward pair",trial=1:nrow(sim_a15_valnoise_skew$plot_df_list[[2]]))
comb_plot_df <- rbind(plot_df1,plot_df2)

dq_df <- ggplot(comb_plot_df,aes(x=trial,y=dQ_mean,group=pair)) +
                geom_line(aes(color=pair)) +
                geom_ribbon(aes(ymin = dQ_mean-2*dQ_sd,
                                ymax = dQ_mean+2*dQ_sd,
                                fill=pair),
                                alpha=.3) +
                scale_colour_manual(values = c("Reward pair"="blue","Affect pair"="red")) +
                scale_fill_manual(values = c("Reward pair"="dodgerblue1","Affect pair"="salmon3")) +
                labs(x="Trial of pair",y="Diff in reward Qs")
 
da_df <- ggplot(comb_plot_df,aes(x=trial,y=dA_mean,group=pair)) +
                geom_line(aes(color=pair)) +
                geom_ribbon(aes(ymin = dA_mean-2*dA_sd,
                                ymax = dA_mean+2*dA_sd,
                                fill=pair),
                                alpha=.3) +
                scale_colour_manual(values = c("Reward pair"="blue","Affect pair"="red")) +
                scale_fill_manual(values = c("Reward pair"="dodgerblue1","Affect pair"="salmon3")) +
                labs(x="Trial of pair",y="Diff in affect Qs")
dq_df
da_df
sim_a15_valnoise_skew$d_cor_grid
```

```{r}
prob_r_new <- rbind(c(rep(1/11,11)),
                    c(rep(1/11,11)),
                    c(rep(0,4),rep(1/6,6),0),
                    c(0,rep(1/6,6),rep(0,4)))
prob_fo_skew_14 <- rbind(c(.2,.3,.2,.05,.05,.05,.03,.03,.03,.03,.03),
                    c(.03,.03,.03,.03,.03,.05,.05,.05,.2,.3,.2),
                    c(rep(0,4),0.05,0.1,0.11,0.21,0.21,0.32,0),
                    c(0,.32,.21,.21,.11,.1,.05,rep(0,4)))
prob_fo_regskew <- rbind(c(.2,.3,.2,.05,.05,.05,.03,.03,.03,.03,.03),
                    c(.03,.03,.03,.03,.03,.05,.05,.05,.2,.3,.2),
                    c(rep(0,4),0.12,0.12,0.13,0.16,0.2,0.27,0),
                    c(0,.27,.2,.16,.13,.12,.12,rep(0,4)))

prob_fo_lightskew <- rbind(c(.2,.3,.2,.05,.05,.05,.03,.03,.03,.03,.03),
                    c(.03,.03,.03,.03,.03,.05,.05,.05,.2,.3,.2),
                    c(rep(0,4),0.13,0.13,0.14,0.16,0.19,0.25,0),
                    c(0,.25,.19,.16,.14,.13,.13,rep(0,4)))

prob_fo_agg_ls <- rbind(c(.3,.2,.12,.07,.06,.05,.05,.04,.04,.04,.03),
                     c(0.03,0.04,0.04,0.04,0.05,0.05,0.06,0.07,0.12,0.2,0.3),
                     c(rep(0,4),0.13,0.13,0.14,0.16,0.19,0.25,0),
                     c(0,.25,.19,.16,.14,.13,.13,rep(0,4)))

prob_fo_agg_rs <- rbind(c(.3,.2,.12,.07,.06,.05,.05,.04,.04,.04,.03),
                     c(0.03,0.04,0.04,0.04,0.05,0.05,0.06,0.07,0.12,0.2,0.3),
                     c(rep(0,4),0.12,0.12,0.13,0.16,0.2,0.27,0),
                     c(0,.27,.2,.16,.13,.12,.12,rep(0,4)))


prob_fo_flat_ls <- rbind(c(.21,.15,.11,.09,.08,.07,.07,.06,.06,.05,.05),
                     c(0.05,0.05,0.06,0.06,0.07,0.07,0.08,0.09,0.11,0.15,0.21),
                     c(rep(0,4),0.13,0.13,0.14,0.16,0.19,0.25,0),
                     c(0,.25,.19,.16,.14,.13,.13,rep(0,4)))

prob_fo_comp_ls <- rbind(c(.25,.17,.12,.09,.07,.06,.06,.05,.05,.05,.04),
                     c(0.04,0.04,0.05,0.05,0.06,0.06,0.07,0.09,0.12,0.17,0.25),
                     c(rep(0,4),0.13,0.13,0.14,0.16,0.19,0.25,0),
                     c(0,.25,.19,.16,.14,.13,.13,rep(0,4)))

prob_fo_flat_rs <- rbind(c(.21,.15,.11,.09,.08,.07,.07,.06,.06,.05,.05),
                     c(0.05,0.05,0.06,0.06,0.07,0.07,0.08,0.09,0.11,0.15,0.21),
                     c(rep(0,4),0.12,0.12,0.13,0.16,0.2,0.27,0),
                      c(0,.27,.2,.16,.13,.12,.12,rep(0,4)))

prob_fo_semicomp_rs <- rbind(c(.23,.16,.12,.09,.07,.06,.06,.06,.05,.05,.05),
                     c(0.05,0.05,0.05,0.06,0.06,0.06,0.07,0.09,0.12,0.16,0.23),
                     c(rep(0,4),0.12,.12,0.13,0.16,0.2,0.27,0),
                      c(0,.27,.2,.16,.13,.12,.12,rep(0,4)))

prob_fo_semicomp_ls <- rbind(c(.23,.16,.12,.09,.07,.06,.06,.06,.05,.05,.05),
                     c(0.05,0.05,0.05,0.06,0.06,0.06,0.07,0.09,0.12,0.16,0.23),
                     c(rep(0,4),0.13,0.13,0.14,0.16,0.19,0.25,0),
                     c(0,.25,.19,.16,.14,.13,.13,rep(0,4)))


# prob_fo_new <- rbind(c(0.05,0.05,0.06,0.06,0.07,0.07,0.08,0.09,0.11,0.15,0.21),
#                       c(.21,.15,.11,.09,.08,.07,.07,.06,.06,.05,.05),
#                       c(rep(0,5),0.13,0.13,0.14,0.16,0.19,0.25),
#                       c(.25,.19,.16,.14,.13,.13,rep(0,5)))
# prob_fo_comp <- rbind(c(0.04,0.04,0.05,0.05,0.06,0.06,0.07,0.09,0.12,0.17,0.25),
#                      c(.25,.17,.12,.09,.07,.06,.06,.05,.05,.05,.04),
#                      c(rep(0,5),0.13,0.13,0.14,0.16,0.19,0.25),
#                      c(.25,.19,.16,.14,.13,.13,rep(0,5)))
# prob_fo_fullskew <- rbind(c(0.05,0.05,0.06,0.06,0.07,0.07,0.08,0.09,0.11,0.15,0.21),
#                       c(.21,.15,.11,.09,.08,.07,.07,.06,.06,.05,.05),
#                       c(rep(0,5),0.05,0.1,0.11,0.21,0.21,0.32),
#                       c(.32,.21,.21,.11,.1,.05,rep(0,5)))
# prob_fo_agg <- rbind(c(0.03,0.04,0.04,0.04,0.05,0.05,0.06,0.07,0.12,0.2,0.3),
#                     c(.3,.2,.12,.07,.06,.05,.05,.04,.04,.04,03),
#                     c(rep(0,5),0.13,0.13,0.14,0.16,0.19,0.25),
#                     c(.25,.19,.16,.14,.13,.13,rep(0,5)))
# prob_fo_init_newskew <- rbind(c(.2,.3,.2,.05,.05,.05,.03,.03,.03,.03,.03),
#                     c(.03,.03,.03,.03,.03,.05,.05,.05,.2,.3,.2),
#                     c(rep(0,5),0.13,0.13,0.14,0.16,0.19,0.25),
#                     c(.25,.19,.16,.14,.13,.13,rep(0,5)))
# prob_fo_skew <- rbind(c(.2,.3,.2,.05,.05,.05,.03,.03,.03,.03,.03),
#                     c(.03,.03,.03,.03,.03,.05,.05,.05,.2,.3,.2),
#                     c(0,0,0,0,.05,.05,.1,.1,.2,.2,.3),
#                    c(.3,.2,.2,.1,.1,.05,.05,0,0,0,0))

```

```{r}
save_sim(sim_a15_valnoise_fo1,path_to_project_directory)
```

```{r}
sim_new$d_cor_grid
sim_skew$d_cor_grid
sim_comp$d_cor_grid
sim_test$d_cor_grid
sim_agg$d_cor_grid
sim_fullskew$d_cor_grid
sim_a15_valnoise_skew$func_inputs
```

```{r}
sim_a15_rerun$d_cor_grid
sim_14$d_cor_grid
sim_regskew$d_cor_grid
sim_14$lcg_list[[2]]
sim_regskew$lcg_list[[2]]
sim_lightskew$d_cor_grid
sim_lightskew$lcg_list[[2]]
sim_flat_ls$d_cor_grid
sim_aggr_ls$d_cor_grid
sim_flat_rs$d_cor_grid
sim_flat_ls$d_cor_grid

sim_flat_ls_weakfo$d_cor_grid
sim_comp_ls$d_cor_grid
sim_semicomp_rs_weakfo$d_cor_grid
sim_semicomp_ls_weakfo$d_cor_grid
sim_comp_ls_weakfo$d_cor_grid
sim_aggr_ls_weakfo$d_cor_grid
```

